# Generated by Django 4.2.10 on 2024-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthyhoos', '0002_group_admin_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
